id: PYSEC-0000-CVE-2022-22846
details: The dnslib package through 0.9.16 for Python does not verify that the ID
  value in a DNS reply matches an ID value in a query.
affected:
- package:
    name: dnslib
    ecosystem: PyPI
    purl: pkg:pypi:dnslib
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 0.9.17
references:
- type: REPORT
  url: https://github.com/paulc/dnslib/issues/30
aliases:
- CVE-2022-22846
modified: "2022-01-10T14:14:00Z"
published: "2022-01-10T14:12:00Z"
