{
    "GSD": {
        "alias": "CVE-2022-1056",
        "description": "Out-of-bounds Read error in tiffcrop in libtiff 4.3.0 allows attackers to cause a denial-of-service via a crafted tiff file. For users that compile libtiff from sources, the fix is available with commit 46dc8fcd.",
        "id": "GSD-2022-1056"
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@gitlab.com",
                "ID": "CVE-2022-1056",
                "STATE": "PUBLIC"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "libtiff",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": "=4.3.0"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "libtiff"
                        }
                    ]
                }
            },
            "credit": [
                {
                    "lang": "eng",
                    "value": "wangdw.augustus@gmail.com"
                }
            ],
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "Out-of-bounds Read error in tiffcrop in libtiff 4.3.0 allows attackers to cause a denial-of-service via a crafted tiff file. For users that compile libtiff from sources, the fix is available with commit 46dc8fcd."
                    }
                ]
            },
            "impact": {
                "cvss": {
                    "attackComplexity": "LOW",
                    "attackVector": "LOCAL",
                    "availabilityImpact": "HIGH",
                    "baseScore": 5.4,
                    "baseSeverity": "MEDIUM",
                    "confidentialityImpact": "NONE",
                    "integrityImpact": "NONE",
                    "privilegesRequired": "NONE",
                    "scope": "UNCHANGED",
                    "userInteraction": "REQUIRED",
                    "vectorString": "AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                    "version": "3.1"
                }
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "Out-of-bounds read in libtiff"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://gitlab.com/libtiff/libtiff/-/issues/391",
                        "refsource": "MISC",
                        "url": "https://gitlab.com/libtiff/libtiff/-/issues/391"
                    },
                    {
                        "name": "https://gitlab.com/libtiff/libtiff/-/merge_requests/307",
                        "refsource": "MISC",
                        "url": "https://gitlab.com/libtiff/libtiff/-/merge_requests/307"
                    },
                    {
                        "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-1056.json",
                        "refsource": "CONFIRM",
                        "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-1056.json"
                    }
                ]
            }
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": []
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@gitlab.com",
                    "ID": "CVE-2022-1056"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "Out-of-bounds Read error in tiffcrop in libtiff 4.3.0 allows attackers to cause a denial-of-service via a crafted tiff file. For users that compile libtiff from sources, the fix is available with commit 46dc8fcd."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": []
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://gitlab.com/libtiff/libtiff/-/merge_requests/307",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://gitlab.com/libtiff/libtiff/-/merge_requests/307"
                        },
                        {
                            "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-1056.json",
                            "refsource": "CONFIRM",
                            "tags": [],
                            "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-1056.json"
                        },
                        {
                            "name": "https://gitlab.com/libtiff/libtiff/-/issues/391",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://gitlab.com/libtiff/libtiff/-/issues/391"
                        }
                    ]
                }
            },
            "impact": {},
            "lastModifiedDate": "2022-03-28T21:04Z",
            "publishedDate": "2022-03-28T19:15Z"
        }
    }
}