id: PYSEC-0000-CVE-2016-1242
package:
  name: tryton
  ecosystem: PyPI
details: file_open in Tryton before 3.2.17, 3.4.x before 3.4.14, 3.6.x before 3.6.12,
  3.8.x before 3.8.8, and 4.x before 4.0.4 allows remote authenticated users with
  certain permissions to read arbitrary files via the name parameter or unspecified
  other vectors.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 3.2.17
  - type: ECOSYSTEM
    introduced: '3.4'
    fixed: 3.4.14
  - type: ECOSYSTEM
    introduced: '3.6'
    fixed: 3.6.12
  - type: ECOSYSTEM
    introduced: '3.8'
    fixed: 3.8.8
  - type: ECOSYSTEM
    introduced: '4.0'
    fixed: 4.0.4
references:
- type: WEB
  url: https://bugs.tryton.org/issue5808
- type: WEB
  url: http://www.debian.org/security/2016/dsa-3656
- type: WEB
  url: http://www.tryton.org/posts/security-release-for-issue5795-and-issue5808.html
aliases:
- CVE-2016-1242
modified: "2017-01-13T02:59:00Z"
published: "2016-09-07T19:28:00Z"
