{
    "GSD": {
        "alias": "CVE-2022-40228",
        "id": "GSD-2022-40228"
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@mitre.org",
                "ID": "CVE-2022-40228",
                "STATE": "RESERVED"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided."
                    }
                ]
            }
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": []
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "psirt@us.ibm.com",
                    "ID": "CVE-2022-40228"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "IBM DataPower Gateway 10.0.3.0 through 10.0.4.0, 10.0.1.0 through 10.0.1.9, 2018.4.1.0 through 2018.4.1.22, and 10.5.0.0 through 10.5.0.2 does not invalidate session after a password change which could allow an authenticated user to impersonate another user on the system. IBM X-Force ID: 235527."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": []
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://www.ibm.com/support/pages/node/6840759",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://www.ibm.com/support/pages/node/6840759"
                        },
                        {
                            "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/235527",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/235527"
                        }
                    ]
                }
            },
            "impact": {},
            "lastModifiedDate": "2022-11-22T19:17Z",
            "publishedDate": "2022-11-22T19:15Z"
        }
    }
}