{
    "GSD": {
        "alias": "CVE-2022-22818",
        "description": "The {% debug %} template tag in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2 does not properly encode the current context. This may lead to XSS.",
        "id": "GSD-2022-22818"
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@mitre.org",
                "ID": "CVE-2022-22818",
                "STATE": "PUBLIC"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "n/a",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": "n/a"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "n/a"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "The {% debug %} template tag in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2 does not properly encode the current context. This may lead to XSS."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "n/a"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://groups.google.com/forum/#!forum/django-announce",
                        "refsource": "MISC",
                        "url": "https://groups.google.com/forum/#!forum/django-announce"
                    },
                    {
                        "name": "https://docs.djangoproject.com/en/4.0/releases/security/",
                        "refsource": "MISC",
                        "url": "https://docs.djangoproject.com/en/4.0/releases/security/"
                    },
                    {
                        "name": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/",
                        "refsource": "CONFIRM",
                        "url": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/"
                    }
                ]
            }
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": []
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2022-22818"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "The {% debug %} template tag in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2 does not properly encode the current context. This may lead to XSS."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": []
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://docs.djangoproject.com/en/4.0/releases/security/",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://docs.djangoproject.com/en/4.0/releases/security/"
                        },
                        {
                            "name": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/",
                            "refsource": "CONFIRM",
                            "tags": [],
                            "url": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/"
                        },
                        {
                            "name": "https://groups.google.com/forum/#!forum/django-announce",
                            "refsource": "MISC",
                            "tags": [],
                            "url": "https://groups.google.com/forum/#!forum/django-announce"
                        }
                    ]
                }
            },
            "impact": {},
            "lastModifiedDate": "2022-02-03T02:15Z",
            "publishedDate": "2022-02-03T02:15Z"
        }
    }
}