id: PYSEC-2020-138
package:
  name: tensorflow
  ecosystem: PyPI
summary: Vulnerability in tensorflow
details: In Tensorflow before version 2.4.0, an attacker can pass an invalid `axis`
  value to `tf.quantization.quantize_and_dequantize`. This results in accessing a
  dimension outside the rank of the input tensor in the C++ kernel implementation.
  However, dim_size only does a DCHECK to validate the argument and then uses it to
  access the corresponding element of an array. Since in normal builds, `DCHECK`-like
  macros are no-ops, this results in segfault and access out of bounds of the array.
  The issue is patched in eccb7ec454e6617738554a255d77f08e60ee0808 and TensorFlow
  2.4.0 will be released containing the patch. TensorFlow nightly packages after this
  commit will also have the issue resolved.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    fixed: eccb7ec454e6617738554a255d77f08e60ee0808
  - type: ECOSYSTEM
    fixed: 2.4.0
references:
- type: WEB
  url: https://github.com/tensorflow/tensorflow/commit/eccb7ec454e6617738554a255d77f08e60ee0808
- type: WEB
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-rrfp-j2mp-hq9c
- type: WEB
  url: https://github.com/tensorflow/tensorflow/issues/42105
aliases:
- CVE-2020-15265
modified: "2020-11-03T01:51:00Z"
published: "2020-10-21T21:15:00Z"
